input {
  file {
    path => "/var/log/*.log"
    start_position => "beginning"
  }
}

output {
  opensearch {
    hosts => ["http://localhost:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}