apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-monitoring-kube-prometheus-alertmanager
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    route:
      receiver: 'slack-notifications'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h

    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - api_url: ${SLACK_WEBHOOK_URL}
            channel: '#ajay-devops'